# Form implementation generated from reading ui file 'f:\Auto-PTS-Designer\gui\home.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 732)
        Form.setMinimumSize(QtCore.QSize(412, 732))
        Form.setMaximumSize(QtCore.QSize(412, 732))
        Form.setStyleSheet("background: #fff;")
        self.btn_design = QtWidgets.QPushButton(parent=Form)
        self.btn_design.setGeometry(QtCore.QRect(20, 480, 371, 41))
        self.btn_design.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_design.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_design.setObjectName("btn_design")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.activity = QtWidgets.QTextEdit(parent=Form)
        self.activity.setGeometry(QtCore.QRect(20, 60, 371, 361))
        self.activity.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"")
        self.activity.setObjectName("activity")
        self.btn_url_1010 = QtWidgets.QPushButton(parent=Form)
        self.btn_url_1010.setGeometry(QtCore.QRect(20, 430, 371, 41))
        self.btn_url_1010.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_url_1010.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_url_1010.setObjectName("btn_url_1010")
        self.btn_design_1 = QtWidgets.QPushButton(parent=Form)
        self.btn_design_1.setEnabled(True)
        self.btn_design_1.setGeometry(QtCore.QRect(20, 530, 371, 41))
        self.btn_design_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_design_1.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_design_1.setObjectName("btn_design_1")
        self.btn_design_2 = QtWidgets.QPushButton(parent=Form)
        self.btn_design_2.setEnabled(True)
        self.btn_design_2.setGeometry(QtCore.QRect(20, 580, 371, 41))
        self.btn_design_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_design_2.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_design_2.setObjectName("btn_design_2")
        self.btn_design_3 = QtWidgets.QPushButton(parent=Form)
        self.btn_design_3.setEnabled(True)
        self.btn_design_3.setGeometry(QtCore.QRect(20, 630, 371, 41))
        self.btn_design_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_design_3.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_design_3.setObjectName("btn_design_3")
        self.btn_design_4 = QtWidgets.QPushButton(parent=Form)
        self.btn_design_4.setEnabled(True)
        self.btn_design_4.setGeometry(QtCore.QRect(20, 680, 371, 41))
        self.btn_design_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_design_4.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"background: #009900;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"")
        self.btn_design_4.setObjectName("btn_design_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_design.setText(_translate("Form", "Thiết kế 10x15"))
        self.label.setText(_translate("Form", "Nhật ký hoạt động"))
        self.btn_url_1010.setText(_translate("Form", "Chọn thư mục thiết kế"))
        self.btn_design_1.setText(_translate("Form", "Thiết kế 7x10"))
        self.btn_design_2.setText(_translate("Form", "Thiết kế 6x9"))
        self.btn_design_3.setText(_translate("Form", "Thiết kế 13x18"))
        self.btn_design_4.setText(_translate("Form", "Thiết kế 9x13"))
