# Form implementation generated from reading ui file 'f:\Auto-PTS-Designer\gui\main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 732)
        Form.setMinimumSize(QtCore.QSize(360, 732))
        Form.setMaximumSize(QtCore.QSize(360, 732))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Form.setStyleSheet("background: #f0f2f5;")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setStyleSheet("background: #f7f7f7;\n"
"padding: 7px 0;\n"
"border: 1px solid #ccc;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"font-weight: 500;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.activity = QtWidgets.QTextEdit(parent=self.widget_2)
        self.activity.setStyleSheet("border: 1px solid #ccc;\n"
"border-top: none;\n"
"border-top-left-radius: 0;\n"
"border-top-right-radius: 0;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"background: #fff;")
        self.activity.setObjectName("activity")
        self.verticalLayout_2.addWidget(self.activity)
        self.btn_url_1010 = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_url_1010.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_url_1010.setStyleSheet("background: #0d6efd;\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"margin-top: 11px;\n"
"")
        self.btn_url_1010.setObjectName("btn_url_1010")
        self.verticalLayout_2.addWidget(self.btn_url_1010)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setStyleSheet("background: #fff;\n"
"border: 1px solid #ccc;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-right: none;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_2.setStyleSheet("padding: 7px 0;\n"
"font-weight: 500;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.input_69 = QtWidgets.QRadioButton(parent=self.widget_4)
        self.input_69.setMinimumSize(QtCore.QSize(0, 22))
        self.input_69.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.input_69.setFont(font)
        self.input_69.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.input_69.setStyleSheet("font-size: 14px;\n"
"border: none;")
        self.input_69.setChecked(True)
        self.input_69.setObjectName("input_69")
        self.verticalLayout_4.addWidget(self.input_69)
        self.input_710 = QtWidgets.QRadioButton(parent=self.widget_4)
        self.input_710.setMinimumSize(QtCore.QSize(0, 22))
        self.input_710.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_710.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.input_710.setStyleSheet("border: none;\n"
"font-size: 14px;")
        self.input_710.setObjectName("input_710")
        self.verticalLayout_4.addWidget(self.input_710)
        self.input_1015 = QtWidgets.QRadioButton(parent=self.widget_4)
        self.input_1015.setMinimumSize(QtCore.QSize(0, 22))
        self.input_1015.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_1015.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.input_1015.setStyleSheet("font-size: 14px;\n"
"border: none;")
        self.input_1015.setObjectName("input_1015")
        self.verticalLayout_4.addWidget(self.input_1015)
        self.input_913 = QtWidgets.QRadioButton(parent=self.widget_4)
        self.input_913.setMinimumSize(QtCore.QSize(0, 22))
        self.input_913.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_913.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.input_913.setStyleSheet("font-size: 14px;\n"
"border: none;\n"
"")
        self.input_913.setObjectName("input_913")
        self.verticalLayout_4.addWidget(self.input_913)
        self.input_1318 = QtWidgets.QRadioButton(parent=self.widget_4)
        self.input_1318.setMinimumSize(QtCore.QSize(0, 22))
        self.input_1318.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_1318.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.input_1318.setStyleSheet("font-size: 14px;\n"
"border: none;")
        self.input_1318.setObjectName("input_1318")
        self.verticalLayout_4.addWidget(self.input_1318)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setStyleSheet("background: #fff;\n"
"border: 1px solid #ccc;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-left: none;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_3.setStyleSheet("padding: 7px 0;\n"
"font-weight: 500;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.input_60 = QtWidgets.QRadioButton(parent=self.widget_5)
        self.input_60.setMinimumSize(QtCore.QSize(0, 22))
        self.input_60.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_60.setStyleSheet("border: none;\n"
"font-size: 14px;")
        self.input_60.setChecked(True)
        self.input_60.setObjectName("input_60")
        self.verticalLayout_3.addWidget(self.input_60)
        self.input_50 = QtWidgets.QRadioButton(parent=self.widget_5)
        self.input_50.setMinimumSize(QtCore.QSize(0, 22))
        self.input_50.setMaximumSize(QtCore.QSize(16777215, 22))
        self.input_50.setStyleSheet("border: none;\n"
"font-size: 14px;")
        self.input_50.setObjectName("input_50")
        self.verticalLayout_3.addWidget(self.input_50)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_7.setStyleSheet("border: none;")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_4.setStyleSheet("padding: 7px 0;\n"
"font-weight: 500;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.msg_yes = QtWidgets.QRadioButton(parent=self.widget_7)
        self.msg_yes.setStyleSheet("font-size: 14px;\n"
"border: none;\n"
"")
        self.msg_yes.setChecked(True)
        self.msg_yes.setObjectName("msg_yes")
        self.verticalLayout_5.addWidget(self.msg_yes)
        self.msg_no = QtWidgets.QRadioButton(parent=self.widget_7)
        self.msg_no.setStyleSheet("font-size: 14px;\n"
"border: none;\n"
"")
        self.msg_no.setObjectName("msg_no")
        self.verticalLayout_5.addWidget(self.msg_no)
        self.verticalLayout_3.addWidget(self.widget_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_submit = QtWidgets.QPushButton(parent=self.widget_6)
        self.btn_submit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_submit.setStyleSheet("background: #0d6efd;\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"max-width: 120px;\n"
"")
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout_2.addWidget(self.btn_submit)
        self.verticalLayout.addWidget(self.widget_6)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nhật ký hoạt động"))
        self.btn_url_1010.setText(_translate("Form", "Chọn đường dẫn"))
        self.label_2.setText(_translate("Form", "Cỡ thiết kế"))
        self.input_69.setText(_translate("Form", "6x9"))
        self.input_710.setText(_translate("Form", "7x10"))
        self.input_1015.setText(_translate("Form", "10x15"))
        self.input_913.setText(_translate("Form", "9x13"))
        self.input_1318.setText(_translate("Form", "13x18"))
        self.label_3.setText(_translate("Form", "Khổ giấy"))
        self.input_60.setText(_translate("Form", "60 cm"))
        self.input_50.setText(_translate("Form", "50 cm"))
        self.label_4.setText(_translate("Form", "Thông báo"))
        self.msg_yes.setText(_translate("Form", "Có"))
        self.msg_no.setText(_translate("Form", "Không"))
        self.btn_submit.setText(_translate("Form", "Bắt đầu"))
